name: Completion

on:
  pull_request:
    types:
      - labeled
      - unlabeled
  check_suite:
    types:
      - completed
  status: {}

jobs:
  maybe_merge:
    name: Merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Automerge
        uses: devmasx/merge-branch@v1.1.0
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          label_name: 'Ready to merge'
          target_branch: 'master'
