name: Completion

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  maybe_merge:
    name: Merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Automerge
        uses: pascalgn/automerge-action@v0.8.0
        env:
          MERGE_RETRIES: 10
          MERGE_RETRY_SLEEP: 30000
          MERGE_LABELS: 'Ready to merge,!Do not merge'
          MERGE_METHOD: 'rebase'
          UPDATE_METHOD: 'rebase'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
