name: Completion

on:
  pull_request:
    types:
      - labeled
      - ready_for_review
      - review_request_removed
      - review_requested
      - synchronize
      - unlabeled
  pull_request_review:
    types:
      - dismissed
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  maybe_merge:
    name: Merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Automerge
        uses: squalrus/merge-bot@v0.4.1
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          reviewers: true
          labels: 'Ready to merge'
          blocking-labels: 'Do not merge'
          checks: true
          method: rebase
