name: PR

on:
  push:
    branches-ignore:
      - master
      - gh-pages
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  create_pull_request:
    name: Create
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Create a PR
        id: cpr
        uses: repo-sync/pull-request@v2.0.1
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          source_branch: '${{ github.ref }}'
          pr_reviewer: devlato
          pr_assignee: devlato
          pr_label: '2.0.0'
          pr_milestone: '2.0.0'
          pr_title: 'Merge ${{ github.ref }} into master'
          pr_body: |
            <!-- START pr-commits -->
            <!-- END pr-commits -->
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
      - name: Done
        run: echo Done
        if: success() || failure()
  update_pr_body:
    name: Create
    needs: [create_pull_request]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Sets PR body
        uses: technote-space/pr-commit-body-action@v1.4.1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
