name: PR

on:
  push:
    branches-ignore:
      - master
      - gh-pages
    tags-ignore:
      - '*'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  create_pull_request:
    name: Create or update a PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Create a PR
        id: cpr
        uses: repo-sync/pull-request@v2.0.1
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          pr_reviewer: devlato
          pr_assignee: devlato
          pr_label: '2.0.0'
          pr_milestone: '2.0.0'
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
      - name: Done
        run: echo Done
        if: success() || failure()
  update_pr_body:
    name: Update PR body
    needs: [create_pull_request]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Generate PR changelog
        id: changelog
        uses: metcalfc/changelog-generator@v0.2.3
        with:
          myToken: '${{ secrets.GITHUB_TOKEN }}'
      - name: Update PR body
        uses: AsasInnab/pr-body-action@v1
        with:
          body: '${{ steps.changelog.outputs.changelog }}'
          base-ref: 'master'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
