name: PR

on:
  pull_request: {}
  push:
    branches-ignore:
      - master
      - gh-pages

jobs:
  create_pull_request:
    name: Create
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Create a PR
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          reviewers: devlato
          assignees: devlato
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
      - name: Done
        run: echo Done
        if: success() || failure()
